### ISSUE TITLE
Deadzone problem splatoon ps3 controller

### ISSUE THREAD

**Issue by Kekskruemel** [Maschell/hid_to_vpad#1]
First thx for the work.

I have a problem with my ps3 controller and splatoon.
I disabled the gyro to use the right stick for aiming.

After moving the right stick the aiming is still moving if the stick is in the neutral position. So maybe there is a minimal bigger deadzone needed.

Also moving the right stick to the far left, the aiming direction switch from one to the other moment to right, maybe also some deadzone problem.

Thx & Greetings

**Comment by Maschell** [comment]
Should be fixed now!
