### ISSUE TITLE
Mouse glitch

### ISSUE THREAD

**Issue by Nico8400** [Maschell/hid_to_vpad#10]
I tried a keyboard/mouse config to play splatoon the keyboard is working but if I move the mouse it "spams" the ZR and the R button, when I click with the left/right/middle click it aims down and when I use    additional clicks(mouse4 and mouse5) it aims up.
I tried the two last version of HID to Vpad but nothing change; I also tried with with two different mouse,
the razer Ouroboros and the mad catz R.A.T. 3 both of them have "additional" clicks and DPI change on it.
btw I love your work and I hope that this will be fixed.

**Comment by Maschell** [comment]
Will be fixed with the upcming version. But thanks for the report!
