### ISSUE TITLE
How do I build?

### ISSUE THREAD

**Issue by jv110** [Maschell/hid_to_vpad#11]
I'm making a program, and the Wii U side of it is a mod of HIDtoVPAD, but I can't get it to build!
It complains about GLM. Maybe I got the wrong version, why don't you put it here in the repo?

I'm using Windows, is that the problem?

**Comment by jv110** [comment]
Updated GLM and it fixed it, but now it gives this error:
```c:/devkitPro/libwiiu/homebrew/hid_to_vpad/src/glm/detail/_vectorize.hpp:76:41: note:   no known conversion for argument 1 from '<unresolved overloaded function type>' to 'float (*)(float)'
make[1]: *** [cpp_to_c_util.o] Error 1
make: *** [build] Error 2```

**Comment by Maschell** [comment]
You need to add the files that came with loadiine gx2 to your devkit folder.
https://github.com/dimok789/loadiine_gx2/releases/tag/v0.2

But you're right, I should add this to the readme

**Comment by Maschell** [comment]
No more questions for 8 months, I guess I can close this. Otherwise just open another
