### ISSUE TITLE
DS4 Stick not working properly

### ISSUE THREAD

**Issue by MuriloMJ** [Maschell/hid_to_vpad#13]
For some reason my DS4 stick is not working properly, when I move it left/right it moves very slowly and sometimes inverted

**Comment by MuriloMJ** [comment]
Forgot to mention that I'm using latest version of loadiine and testing on super smash bros

**Comment by DTK21** [comment]
Question: Did you use the same code for the .ini in the controller code thread? I know it didn't work at all for me and also maybe a possible fix that was in a reply to my issue "PS3 Controller problem"

**Comment by Maschell** [comment]
Should be fixed with the new version. If you still have the problems, make sure you have no .ini file on your sd card with strange values
