### ISSUE TITLE
New Model PS4 Controller not working at all

### ISSUE THREAD

**Issue by GinBunBun** [Maschell/hid_to_vpad#16]
I know the program is supposed to have built in support for the PS4 controller. I recently bought a ps4 pro and it came with sony's updated ps4 controller the one with the light bar showing in the touch pad. I will not woke at all. Even in the HID test program it shows nothing plugged in. I tried different usb ports, different usb cables nothing works. The controller is brand new and works perfectly on PC and PS4 pro obviously but I just dont understand why the newer ps4 controller model wont get detected. Aside from the lightbar differences its identical from what I understand. Any help on this would be much appreciated.

**Comment by Maschell** [comment]
I don't have the controllen (not even a PS4) so its hard for me to test and implement it.  But I'll see what I can do about it

**Comment by GinBunBun** [comment]
Yeah its very strange. I don't know if it helps but sony said that with the new controller they changed how it sends information through usb. For example it sends direct input data through the usb. What that means for gameplay is less latency than using wireless. That's what they said anyway.

**Comment by andreomago** [comment]
If it helps in any way, my NDS4 works perfectly via USB with no add-on program in NINTENDONT

**Comment by Maschell** [comment]
Nintendon't is using his own USB driver.
HIDtoVPAD is using the built in one from the WiiU OS.

However, now the new DS4 can be used in combination with the Network Client
http://gbatemp.net/threads/hid-to-vpad-network-client.466150/

**Comment by Necklaces** [comment]
Apologies for being ignorant, as I'm not entirely sure how this works, but would it be possible to make the NDS4 work via USB? I don't want to connect my WiiU to the internet (or a net at all).

**Comment by piratesephiroth** [comment]
it can work on the wii u if it can connect to the PC without any special driver
