### ISSUE TITLE
PS3 Controller problem

### ISSUE THREAD

**Issue by DTK21** [Maschell/hid_to_vpad#17]
I'm on the default config(I guess) because I have no idea where or how to change inputs. But the analog isn't working like it should. Only input it does is for analog up and down goes right and left, while right and left do nothing

Also the ps3 middle button doesn't bring up the home menu

**Comment by soragranda** [comment]
Hi! did you solved the problem?, I found a ini code from a user in gbatemp, his username es WaveSmash, it works surprisingly good!, everything is working fine!(well i didnt prove the home buttom yet, but the triggers and every other buttoms its fine!

`[vid=0x054c,pid=0x0268]
[IgnoreDefault]

[gamepad]
VPAD_BUTTON_A = DS3_BUTTON_CIRCLE
VPAD_BUTTON_B = DS3_BUTTON_CROSS
VPAD_BUTTON_X = DS3_BUTTON_TRIANGLE
VPAD_BUTTON_Y = DS3_BUTTON_SQUARE
VPAD_BUTTON_MINUS = DS3_BUTTON_SELECT
VPAD_BUTTON_PLUS = DS3_BUTTON_START

//VPAD_BUTTON_HOME = DS3_BUTTON_GUIDE

VPAD_BUTTON_STICK_L = DS3_BUTTON_L3
VPAD_BUTTON_STICK_R = DS3_BUTTON_R3

DPAD_MODE = DS3_DPAD_MODE
VPAD_BUTTON_LEFT = DS3_BUTTON_LEFT
VPAD_BUTTON_RIGHT = DS3_BUTTON_RIGHT
VPAD_BUTTON_UP = DS3_BUTTON_UP
VPAD_BUTTON_DOWN = DS3_BUTTON_DOWN

VPAD_L_STICK_X = DS3_STICK_L_X
VPad_L_Stick_X_MinMax = 0x00,0xFF
VPad_L_Stick_X_Deadzone = 0x06
VPAD_L_STICK_Y = DS3_STICK_L_Y
VPad_L_Stick_Y_MinMax = 0x00,0xFF
VPad_L_Stick_Y_Deadzone = 0x06
VPAD_R_STICK_X = DS3_STICK_R_X
VPad_R_Stick_X_MinMax = 0x00,0xFF
VPad_R_Stick_X_Deadzone = 0x06
VPAD_R_STICK_Y = DS3_STICK_R_Y
VPad_R_Stick_Y_MinMax = 0x00,0xFF
VPad_R_Stick_Y_Deadzone = 0x06

VPAD_BUTTON_L = DS3_BUTTON_L1
VPAD_BUTTON_ZL = DS3_BUTTON_L2
VPAD_BUTTON_R = DS3_BUTTON_R1
VPAD_BUTTON_ZR = DS3_BUTTON_R2

PAD_COUNT = 0x01` 

copy that code in a notepad or text edit app then rename the source code ".ini" and put it in the folder "controller" in the wiiu folder, I was trying like crazy to make it works, my ps3 controller is a cechzc2u btw!

**Comment by DTK21** [comment]
Oh snap this looks awesome, sadly I can't test this out just yet busy held on things

But I wonder if it'll work for ps4 controller by just changing all DS3 to DS4

**Comment by sirjecht** [comment]
THANK YOU so much you fixed the bug. Was spoofing my xbox elite controller to a ps3 input was thinking it was the spoofer at fault and not hid to vpad. but your quick script fixed the default ps3 and now it works flawlessly thanks sora!

**Comment by soragranda** [comment]
You're welcome!, I just wanted to help others(I know that feeling of can't use something that you want to, trying to find a way to make it work properly... So, to improve the app and help the community! :D).

**Comment by Maschell** [comment]
Should be fixed in the new versions!
