### ISSUE TITLE
Mouse doesn't work

### ISSUE THREAD

**Issue by Kekskruemel** [Maschell/hid_to_vpad#2]
Hi,
like mentioned in the IRC, my mouse can only move up and down not right and left.

You wrote it's because of switched bytes for movement and mouseclick.

Here is the pastebin

http://pastebin.com/YRMfLJGk

Thx & Greetings

**Comment by Maschell** [comment]
WIll be fixed in the upcoming version

**Comment by Maschell** [comment]
Should be fixed now
