### ISSUE TITLE
Enable/Disable Rumble in Settings

### ISSUE THREAD

**Issue by TheInsaneDarkOne** [Maschell/hid_to_vpad#20]
Hey there! Doing great? First of all, your project here is really amazing and I´m even thinking on helping you out with a contribution later, just knew this mod yesterday

The thing is, everything is working fine with the GC adapter, even with four controllers but, I noticed that in the second slot, sometimes the rumble starts at random and keeps like that at non-stop (the controller still works, but gets the non-stop vibration)

Is there something wrong with the rumble feature? In fact, I would even like to have no rumble at all if possible (like an option in the menu), but I´m not sure if the software has any option to change that

Again, fantastic work and I hope you can keep improving it, but, just need to know better about this issue to make the best use here!

Thanks for the project! :)

**Comment by MrPotaDos** [comment]
With the GC adapter I'm pretty sure the gray USB plug is for controller rumble so just leave that unplugged. One thing that would be great to have is the option to set the amount of rumble in the config files.

**Comment by TheInsaneDarkOne** [comment]
Yeah, I tested that and, oddly enough, seems that even with one plug, the controller all rumbles like nothing never happened! XD

When I tried, attaching only the black one left things with no response, so, used only the gray connector for the runs on Mario Kart and felt the same, the controllers still rumble

The good thing is that since I updated the program version into the latest nightly build, the problem seems to have stopped, but, as we mentioned, it would be nice if we could have control on the rumble feature in a future release

Thanks for the tip, just to be sure, will re-try to use only the black connector next time! :)

**Comment by Maschell** [comment]
Can you check if problem is still present in this nightly?
https://github.com/Maschell/hid_to_vpad/releases/tag/HIDtoVPAD-v0.9h-nightly-0c92879

**Comment by TheInsaneDarkOne** [comment]
Just checked it yesterday with some friends and yeah, seems the problem is gone! :)

Played a single race in MK (sometimes the other port controllers started rumbling randomly in this cases) and, a multiplayer cup with three friends, and yeah, no issues to report!

Now only the option to turn it on and off would be great, but, if it doesn´t happen, no worries, making it work flawlessly is already a big part! Thanks for all the effort so far! :)

**Comment by Maschell** [comment]
Implemented with commit 11f9e7f
