### ISSUE TITLE
Left Stick on GameCube Controller?

### ISSUE THREAD

**Issue by SSonic125** [Maschell/hid_to_vpad#23]
There seems to be a bit of a problem with the left stick when using a GameCube controller. In some games it doesn't show as much but in Twilight Princess and Wind Waker it seems like the stick doesn't go as far as it should when pushing it to the all the way. In the map in Twilight Princess the cursor moves really slow in the normal 4 directions and goes fast when going diagonally. In Wind Waker it looks like you're not running at full speed.

**Comment by Maschell** [comment]
You can creating a config file with an lower maximum value. Maybe something like this:
```
[vid=0x057e,pid=0x0337]
VPAD_L_STICK_X_MINMAX        =   0x1E,0xD8 //Default 0x1E,0xE5
VPAD_L_STICK_Y_MINMAX        =   0x18,0xD8 //Default 0x18,0xE1
```
Replace the 0xD8 with any maximum you want to test (I would go down in small steps) until everything is working.
(save it in a file with the extension .ini and put it in sd:/wiiu/controller)

You can find more information about the configs in the controller patcher wiki (linked in the readme)

**Comment by SSonic125** [comment]
So I ended up setting the stick to <br>  VPAD_L_STICK_X_MINMAX        =   0x1E,0x8B </br>VPAD_L_STICK_Y_MINMAX        =   0x18,0x87
and found out that making the max a bit lower than that makes the left stick go up and to the right. It seems like the stick is off center which explains why trying to move diagonally down to the left is still slow. Is there any way to recenter the stick in the config?

**Comment by Maschell** [comment]
These value are probabaly wrong, because normally the center is at 0x80. Are you using the official GC-adapter?

**Comment by SSonic125** [comment]
I'm using the Mayflash 4 Slot adapter but it never had any problem when playing Smash Wii U or Dolphin.

**Comment by pmack100** [comment]
I'm having a similar problem too with a mayflash adapter where the cursor in twilight princess slows down when moving diagonally. Have you found any values that fix this?

**Comment by SSonic125** [comment]
After messing around with it some more I found the values
[vid=0x057e,pid=0x0337]
VPAD_L_STICK_X_MINMAX        =   0x1E,0xC8 //Default 0x1E,0xE5
VPAD_L_STICK_Y_MINMAX        =   0x1E,0xC8 //Default 0x18,0xE1
to come close to fixing it. Moving the cursor mostly works fine now, it only slows when moving the stick in a certain spot to the upper left.

**Comment by pmack100** [comment]
so that fixed my left stick but now i notice the right stick after trying to fix the values for that slows when going anywhere to the lower left and straight down, any ideas on how to fix this?

**Comment by Maschell** [comment]
I'll add support for he GC-Adapter in the following days for HIDTest. Then you can check the actual values instead of guessing them

**Comment by Maschell** [comment]
Can you try this version of hidtest on your Wiiu? It should display the raw data of the controller in slot 1. This way you can see the min/max values for each stick/axis
[hidtest.zip](https://github.com/Maschell/hid_to_vpad/files/966638/hidtest.zip)
(I didn't test the file, but it should work)

**Comment by pmack100** [comment]
This works great, thank you!
