### ISSUE TITLE
Loadiine support

### ISSUE THREAD

**Issue by gjimenezf** [Maschell/hid_to_vpad#24]
I have tried using the latest version of hidtovpad 0.9h with loaddine 0.3 latest build but cant get it to work. Is it compatible or no?

**Comment by Maschell** [comment]
It's not possible to chain multiple homebrew programs. Loadiine has built in hid support, but only for the gamepad.
Support for pro controller emulation is currently not planned.

**Comment by Maschell** [comment]
Loadiine now used the newest controller_patcher engine.
Still no support for pro controller though.
