### ISSUE TITLE
hid to vpad steals unused hid inputs(gc controller) when using different hid inputs(switch pro)

### ISSUE THREAD

**Issue by Zarklord** [Maschell/hid_to_vpad#27]
basicaly this:
switch pro mapped to pro1 with nothing else mapped
go to smash it wont use gc controllers anymore

**Comment by Maschell** [comment]
Probably the GC-Adapter only register itself to our HIDClient, not the SSBU one. Need to look deeper in it.

**Comment by Zarklord1** [comment]
alright just wanted to bring it to your attention
