### ISSUE TITLE
Black Screen WiiU 5.5.1 HB Freezes

### ISSUE THREAD

**Issue by gastonestevez** [Maschell/hid_to_vpad#28]
Hi, I have tried to run hid_to_vpad almost 30 times, and when I exec the app in home-brew, the screen goes black, and the only way to exit, is hard-resetting.  I installed haxchi, and it worked perfectly only one time. 
Please help me, i'm tired resetting the Wiiu without success.
Thank you very much!!

**Comment by Maschell** [comment]
Can you try the newest nightly and a fresh SD Card? Maybe some config-file is broken?

**Comment by gastonestevez** [comment]
Hi Maschell, thanks for your quick response . I solved it downloading hidToVpad nightly from the home brew store , but, if I do a fresh copy to sd card from my pc, it crashes every time I open. 
The solution works perfectly , the only mistake I discover is that when I open the browser, the wiiu  freezes, but is a small detail, i can resolve it restarting the console. Thank you very much for all.

**Comment by Maschell** [comment]
Yes, currently opening the Browser is broken.. I'm glad it's working now
