### ISSUE TITLE
Add French translation

### ISSUE THREAD

**Issue by jlozes** [Maschell/hid_to_vpad#33]
Could you add this French translation file to your project?

If there is an other method to do project contributions, let me know cause I'm not very familiar with Github.

[french.zip](https://github.com/Maschell/hid_to_vpad/files/987009/french.zip)

**Comment by Maschell** [comment]
Hey, thanks!
But some texts are too long. They can't longer than the english orignal texts.

**Comment by jlozes** [comment]
I've reduced some texts but it will be difficult to do better than that. Tell me if it's good now.

[french.zip](https://github.com/Maschell/hid_to_vpad/files/987320/french.zip)
