### ISSUE TITLE
Bug with the nightly upload on Apps store

### ISSUE THREAD

**Issue by jlozes** [Maschell/hid_to_vpad#34]
I think there is a problem with the auto-upload function on the Apps Store. The folder "languages" seems to be replaced by a symblink or something like that and the folder is not present on the Apps Store version.

The last zip of the nightly build weigh is 2113 KO for the Github version against 2090 KO for the Store version.

**Comment by Maschell** [comment]
It's but thanks for reporting. Currently the languages are not supported by the app store.

**Comment by Maschell** [comment]
It's fixed now.
