### ISSUE TITLE
Black Screen?

### ISSUE THREAD

**Issue by FlashGamer99** [Maschell/hid_to_vpad#36]
So when I would used HIDtoVPAD every other day, it would work fine. But yesterday, it suddenly just stopped, I would load Homebrew and launch it but it is just a black screen. Any solution or other reports on this probblem? I have downloaded and tried every build and none are working. It isnt the SD card because Ive tried on 4 different ones. Its not the wii U as I own and have tried 2. Please help asap, thank you :)

**Comment by Maschell** [comment]
Did you try starting it without config files on the sd card and no USB Controller attached to the console?

**Comment by FlashGamer99** [comment]
Actually I haven't tried it completely without config files. But I have tried with and without controllers plugged in

**Comment by Maschell** [comment]
Probably same issue as #43 and #35
