### ISSUE TITLE
Add vWii Support?

### ISSUE THREAD

**Issue by SirBeethoven** [Maschell/hid_to_vpad#4]
Wow! This app is amazing! Would you be able to find out if you can patch the vWii Mode with this? That would be amazing! Thank you for such a great app!

**Comment by Maschell** [comment]
Doing this for vWii (and Wii) is possible (e.g. with https://github.com/Chadderz121/brainslug-wii), but its much easier to do on the WiiU. Nothing for the vWii is planned

**Comment by SirBeethoven** [comment]
Cool! That's ok, I'm excited for the latest release though!

**Comment by MegaSuperab** [comment]
It would most likely be Wii homebrew.

**Comment by Maschell** [comment]
Like MegaSuperab said, this wouldn't be an enhancement of HIDtoVPAD but a completly new project.
Closing it. I'll post here if I'll ever make a Wii Version of this tool.
