### ISSUE TITLE
Latest stable version does not have a pre-built release.

### ISSUE THREAD

**Issue by HowManyNamesHaveBeenTaken** [Maschell/hid_to_vpad#42]
The current stable version of HID To VPAD (HIDtoVPAD-v0.9j-nightly-cf54450) does not have a pre-compiled release. Following the link available on both the GBATemp page and the project's github front-page ( https://github.com/Maschell/hid_to_vpad/releases/latest ) will lead to a download page that only offers source code. Considering the fact that this release is the newest one, has a fix for games like Splatoon in the form of being able to disable network support, and that its directly linked to on the app's main discussion page, means that it may cause confusion for new users when they try to download the newest release.

(P.S) On page 73 of the GBATemp, you linked to a build of HID To VPAD that had the ability to disable the network controller support (https://github.com/Maschell/hid_to_vpad/releases/tag/HIDtoVPAD-v0.9j-nightly-c6ddfdc) however, it now just leads to a 404.

**Comment by Maschell** [comment]
Now the newest version should have proper pre-compiled versions
