### ISSUE TITLE
HID to VPAD causes RetroArch to crash upon opening.

### ISSUE THREAD

**Issue by PCKid11** [Maschell/hid_to_vpad#43]
I was unable to open RetroArch after installing it on my Wii U.

Step 1: remove all other apps except for RetroArch. RetroArch now opens.

Step 2: reinstall all other apps, one at a time. When I reinstall hidtovpad, RetroArch once again crashes upon opening.

Therefore, I can conclude that HID to VPAD is causing the issue, not RetroArch.

![Please find attached a screenshot of the error message.](https://user-images.githubusercontent.com/14316037/31877500-9fb43156-b7ce-11e7-97cb-3219d02dcdfb.jpg)

![20171022_171510](https://user-images.githubusercontent.com/14316037/31877598-fee54c78-b7ce-11e7-9632-af993bb624a7.jpg)

**Comment by Maschell** [comment]
It's not HID to VPAD but the .ini files in the controller_patcher folder.
Can you confirm retroarch works when you delete the sd:/wiiu/controller folder?
If this is the case, it would be really cool if you could spot the .ini which is causing it.

**Comment by PCKid11** [comment]
I can confirm that deleting the `sd:/wiiu/controller` folder allows RetroArch to load. Time to start testing ini files...

**Comment by PCKid11** [comment]
ds4new.ini (the first one I added) seems to break RetroArch (same DSI error).

**Comment by PCKid11** [comment]
The presence of ANY `.ini` files seems to break RetroArch (same DSI error). Tested with `ds4new.ini`, `DualShock2.ini`, `GameSirG3w_2Lights.ini` and `hori-rap4-kai.ini` (and I doubt you made mistakes in all four)

**Comment by Maschell** [comment]
Strange. Which retroarch kernel are you using? The last time I used retroarch (fixing a bug last week) I worked with .ini files in the controller folder

**Comment by PCKid11** [comment]
I am using the 2017-10-18 nightly, but I am willing to try updating if that may fix the issue.

**Comment by Maschell** [comment]
Can you send me a copy of your .ini files + retroarch so I can reproduce it on my WiiU?
I just tested the newest retroarch nightly and had no problem

**Comment by PCKid11** [comment]
Sorry, I was away over the weekend and I'd left my laptop at home. I've put a stripped-down version of my SD card on my Google Drive for you to take a look at. [here](https://drive.google.com/open?id=0B8ZSGIE3rheATG9UM2pRRU03dk0). There's only one core included but seeing as it never makes it to the main menu this shouldn't be an issue.

**Comment by Maschell** [comment]
Did you try the new retroarch nightly? I made a pull request with some additional check when parsing the .ini

**Comment by PCKid11** [comment]
Haven't tried yet but I'll try updating both RetroArch and hidtovpad.

**Comment by PCKid11** [comment]
So I updated RetroArch to `2017-10-31` and it started working with HID to VPAD. I then updated hidtovpad to the latest nightly (`2017-10-30`) and everything still worked. However, when I map a controller, everything breaks again (RetroArch freezes at a black screen upon loading).

**Comment by PCKid11** [comment]
OK, this is really odd. Now a bunch of my other apps aren't working! While they don't freeze my Wii U, Homebrew App Store and SaveMii both just crash back to the Homebrew Launcher. I have no idea what's going on here. Those apps both worked before I updated hidtovpad.

**Comment by Maschell** [comment]
"However, when I map a controller, everything breaks again (RetroArch freezes at a black screen upon loading)."
wait -  you don't need to use HID to VPAD before loading retroarch. Retroarch has built in support for HID controller.

But everything is now working?

**Comment by PCKid11** [comment]
Whoops, didn't know about Retroarch and HID devices. However yes everything works now, feel free to close the issue.
