### ISSUE TITLE
[Enhancement] include SwipSwapMe

### ISSUE THREAD

**Issue by cucholix** [Maschell/hid_to_vpad#44]
Basically combine both apps, not sure if would exist possible conflicts between both patches though.

Would be great for Xenoblade Chronicles X, as the game doesn't allow display the map on TV, only in gamepad, so playing with a controller other than gamepad gimp the game experience.

**Comment by Maschell** [comment]
There will be an other solution in the future (=> an app containing all common patches, including a "lite" version of hid to vpad)

**Comment by cucholix** [comment]
Oh, that will be great, those patches include the one to boot fake signed games?

**Comment by Maschell** [comment]
Solution is in progress, see https://github.com/Maschell/WiiUPluginSystem
