### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Fredol7** [Maschell/hid_to_vpad#47]
When I try to save changes with +, the screen goes black and I have to restart my Wii U.

**Comment by QuantumPhoton** [comment]
I have the same issue, it also happens when I exit with the home button

**Comment by Maschell** [comment]
Which version are use using? Which configuration?

**Comment by QuantumPhoton** [comment]
I was using the homebrew launcher 1.3, fixed it updating to 1.4

**Comment by Fredol7** [comment]
I foxed by reinstalling everything so it's probably the same solution as Quantum
