### ISSUE TITLE
Mouse no pointer (white spot)

### ISSUE THREAD

**Issue by mgj7** [Maschell/hid_to_vpad#48]
Mouse always starts in "aim" mode. Switching to "cursors" mode (F1 keyboard) it works but I can't see any pointer (blind mode).
I don't have any mouse.ini in controllers dir, just keyboard.
Any help? Do I have to try different mouses? Is it the lacking of a correct mouse.ini?

**Comment by Maschell** [comment]
Should be fixed with commit https://github.com/Maschell/hid_to_vpad/commit/c9cf99a57b5a0e271db28477bd98fb5c9112148f

**Comment by mgj7** [comment]
thx, M.
m.




     
   	Maschell        20 
febbraio 2018 14:28    
  Should be fixed with commit c9cf99a

—You
 are receiving this because you authored the thread.Reply to this 
email directly, view
 it on GitHub, or mute
 the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Maschell/hid_to_vpad","title":"Maschell/hid_to_vpad","subtitle":"GitHub repository","main_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png"</a>,"avatar_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png"</a>,"action":{"name":"Open in GitHub","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/Maschell/hid_to_vpad">"https://github.com/Maschell/hid_to_vpad"</a>}},"updates":{"snippets":[{
"icon":"PERSON","message":"@Maschell in #48: Should be fixed with commit <a class="moz-txt-link-freetext" href="https://github.com/Maschell/hid_to_vpad/commit/c9cf99a57b5a0e271db28477bd98fb5c9112148f">https://github.com/Maschell/hid_to_vpad/commit/c9cf99a57b5a0e271db28477bd98fb5c9112148f</a>"}],"action":{"name":"View Issue","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/Maschell/hid_to_vpad/issues/48#issuecomment-366977125">"https://github.com/Maschell/hid_to_vpad/issues/48#issuecomment-366977125"</a>}}}
