### ISSUE TITLE
circle ps3 pad doesn't work

### ISSUE THREAD

**Issue by ladyhei** [Maschell/hid_to_vpad#5]
Hi!
the button cirlcle doesn't work, is just me or it's normal ?

**Comment by Maschell** [comment]
Hm, I have no PS3 Pad, so I can't test it. DId anyone else have the problem? Try always to use the newest version

**Comment by Ultracoolguy** [comment]
Me two(well, a clone one)!

**Comment by Ultracoolguy** [comment]
If you want I can test it for you! Just tell me what to do and how to do it and I will start(as long as I can)!

**Comment by Ultracoolguy** [comment]
When the joystick goes left, it reacts as up; when it goes right, it reacts as down; and left and right do nothing. However, the Dpad works well(no issues at all). Loadiine GX2 doesn't have this issue.

**Comment by DTK21** [comment]
I've had that same problem myself
Check issue "PS3 Controller problem" for possible fix

**Comment by Maschell** [comment]
Should be fixed with the newest version
