### ISSUE TITLE
GCN Adapter BEBONCOOL: Dont recognice any input

### ISSUE THREAD

**Issue by D3viloper** [Maschell/hid_to_vpad#73]
Hey Maschell,
I bought a gcn adapter from beboncool and it dont recognice any input. Your hid-test says that it use the correct vid and pid (057e/0337) but its not changing its data when im pressing any buttons,
I hope you can help me

**Comment by Maschell** [comment]
Please provide a solution for everyone else who has the same problem! Thanks!

**Comment by D3viloper** [comment]
I send it back and bought the mayflash one :|
