### ISSUE TITLE
Xbox controller

### ISSUE THREAD

**Issue by squirtlewb** [Maschell/hid_to_vpad#8]
Hello, you guys will disclose some version of HID to vPad compatibility to control Xbox 360?

**Comment by Maschell** [comment]
The Xbox Controller are no HID devices, so we need own drivers for them (+USB access). Nothing I'm able to do though =/

**Comment by squirtlewb** [comment]
thank's 😁

2016-07-29 6:11 GMT-03:00 Maschell <notifications@github.com>:

**Comment by squirtlewb** [comment]
Olá,

Eu acabei de assinar o abaixo-assinado "STF: PELA ANÁLISE DO PEDIDO DE
IMPEACHMENT

CONTRA O MINISTRO ALEXANDRE DE MORAES DO STF" e queria saber se você pode
ajudar assinando também.

A nossa meta é conseguir 3.000.000 assinaturas e precisamos de mais apoio.
Você pode ler mais sobre este assunto e assinar o abaixo-assinado aqui:

http://chng.it/C5Vh4wPrLT

Obrigada/Obrigado!
thiago
