### ISSUE TITLE
Twilight Princess HD 

### ISSUE THREAD

**Issue by jtrain64** [Maschell/hid_to_vpad#9]
Neither the Ps4 or GameCube controller works for z targeting. And when using an item that needs guidance(aiming) isn't working. Otherwise keep up the good work.

**Comment by Maschell** [comment]
Is this bug still present in the newest release?

**Comment by MrPotaDos** [comment]
Another problem with TP is that the GC Controller only seems to work if it's set as the GamePad, the game doesn't detect it as a Pro Controller.

**Comment by Maschell** [comment]
It's a known problem. But it shouldn't really matter, because you don't win anything when the controller is mapped as pro controller instead of the gamepad.
But I will fix it somewhere in the future.

**Comment by MrPotaDos** [comment]
Oh okay, was just wondering if the GC controller set as a Pro Controller would fix the extreme rumble that would happen when riding Epona or hitting grass. I was thinking maybe when set as the GamePad the rumble is set higher due to it being a bigger controller than a GC controller.

**Comment by Maschell** [comment]
The Pro Controller should now work in TP when you press the TV-Button on the gamepad once you're in the menu.
Can you confirm it?
https://github.com/Maschell/hid_to_vpad/releases/tag/HIDtoVPAD-v0.9h-nightly-2872b5e

**Comment by MrPotaDos** [comment]
Just tried it, can confirm it works now. The rumble also seems to be fixed with the Pro Controller settings so that's pretty great too. Thanks a lot for making this homebrew!
