### ISSUE TITLE
where can i find the wifi client for pc put a link please

### ISSUE THREAD

**Issue by GabboXIA** [Maschell/hid_to_vpad#90]
where can i find the wifi client for pc put a link please

**Comment by piratesephiroth** [comment]
https://github.com/Maschell/HIDtoVPADNetworkClient

**Comment by GabboXIA** [comment]
how can i start the client please

**Comment by piratesephiroth** [comment]
you may need to run it from the command line like

`java -jar HIDTest-0.2-nightly-jar-with-dependencies.jar`

You can put that in a bat file next to the jar file and double click it to run.

**Comment by piratesephiroth** [comment]
> 
> 
> how can i start the client please

I noticed that it doesn't run on the latest Java 11 so I made it into a Windows executable (using ikvm).
Try it to see f it works for you too.

[HIDToVPADNetworkClient-0.4.zip](https://github.com/Maschell/hid_to_vpad/files/5792433/HIDToVPADNetworkClient-0.4.zip)

**Comment by GabboXIA** [comment]
_no I started the client version 0.4 from the windows cmd with aministator  with the latest version of java and this here is the code I put java -jar "C: \ Users \ Anonymous \ Downloads \ Trainer Wii U \ HIDToVPADNetworkClient.jar "and went normally_
