### ISSUE TITLE
HID-to-vpad stopped detecting GC adapter

### ISSUE THREAD

**Issue by AngAx209** [Maschell/hid_to_vpad#95]
Hi! i have a GC adapter with the same vid and pid that the tutorial (057e and 0337 respectly) the issue here is, initially it works normally, but now it's stopped detecting the adapter. I tought the problem was from the software in general, i discarded it when trying a keyboard. There were several occasions in wich i tried to modify the configuration of controllers, wanting to access through the Haxchi (until the day of this post, i noticed it was through the mii editor) causing several freezes, maybe that's the reason why it stopped detecting it, i don't know. I tried reinstall thinking cause it a corrupt file (not worked), i tried with another adapter (same vid and pid, not worked). Only can play smash bros normally without open hid-to-vpad, with the same adapter.

**Comment by AngAx209** [comment]
i solved, still undetected in wiiu/switch mode, but I did a manual setup for my nyko adapter in pc mode. It came back to life.

**Comment by Tatechii** [comment]
what did you do to your nyko adapter to work, i have the same problem with a nyko one :(

**Comment by AngAx209** [comment]
I made a custom .ini file with the adapter settings in PC mode. If your adapter is the same as mine, I can pass the file to you.

**Comment by Tatechii** [comment]
thank you so much, indeed i have the same adapter, and i would be so happy if you pass me the file :) thank you

**Comment by AngAx209** [comment]
here's the .ini file for nyko adapter. for ZR and LR buttons, hold Z and press R or L in GameCube Controller. 
the buttons of the joysticks are not configured yet, I do not use it much so I did not configure them.

I hope it works to you.

Sorry for waiting!

[Gamecube_NYKO_Adapter.zip](https://github.com/Maschell/hid_to_vpad/files/7480378/Gamecube_NYKO_Adapter.zip)

**Comment by Tatechii** [comment]
THANK YOU SO MUCH, and where do I put the 
 .ini file to use it?

**Comment by AngAx209** [comment]
In wiiu\controller folder, just paste and enjoy
Pd: switch to pc mode to works
